# Generated by Django 2.2.7 on 2019-12-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191212_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile.jpg', upload_to='profile_pics'),
        ),
    ]
