# Generated by Django 2.2.7 on 2019-12-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscene', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(default='null', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='gallery'),
        ),
    ]
